#games/nine_mens_morris/constants.py
GAME_NAME = "Nine Men's Morris"
GAME_VERSION = "1.0.0"
BOARD_POSITIONS = 24
EMPTY = 0
PLAYER_BLACK = 1
PLAYER_WHITE = 2
FIRST_PLAYER = PLAYER_BLACK
GAME_NOT_STARTED = 0
GAME_RUNNING = 1
GAME_DRAW = 2
GAME_OVER = 3
NO_WINNER = 0
PHASE_PLACEMENT = 0
PHASE_MOVEMENT = 1
PHASE_FLYING = 2
PIECES_PER_PLAYER = 9
MIN_PIECES_TO_PLAY = 3
GAME_MODE_HUMAN_VS_HUMAN = 0
GAME_MODE_HUMAN_VS_AI = 1
GAME_MODE_AI_VS_AI = 2
DEFAULT_GAME_MODE = GAME_MODE_HUMAN_VS_HUMAN
AI_RANDOM = "Random"
AI_EASY = "Easy"
AI_MEDIUM = "Medium"
AI_HARD = "Hard"
BOARD_WIDTH = 500
BOARD_HEIGHT = 500
BOARD_LEFT = 60
BOARD_TOP = 80
OUTER_SIZE = 500
MIDDLE_SIZE = 320
INNER_SIZE = 140
BOARD_LINE_WIDTH = 4
STONE_RADIUS = 18
POSITION_RADIUS = 6
GRID_COLOR = (150, 120, 80)
POSITION_COLOR = (210, 170, 100)
PLAYER_BLACK_COLOR = (30, 30, 30)
PLAYER_WHITE_COLOR = (235, 235, 235)
SELECTED_COLOR = (80, 220, 255)
WIN_LINE_COLOR = (50, 255, 50)
CAPTURE_MARK_COLOR = (255, 180, 50)
POSITION_COORDINATES = {
    0: (BOARD_LEFT,BOARD_TOP,),
    1: (BOARD_LEFT + OUTER_SIZE / 2,BOARD_TOP,),
    2: (BOARD_LEFT + OUTER_SIZE,BOARD_TOP,),
    3: (BOARD_LEFT + (OUTER_SIZE - MIDDLE_SIZE) / 2,BOARD_TOP + (OUTER_SIZE - MIDDLE_SIZE) / 2,),
    4: (BOARD_LEFT + OUTER_SIZE / 2,BOARD_TOP + (OUTER_SIZE - MIDDLE_SIZE) / 2,),
    5: (BOARD_LEFT + OUTER_SIZE - (OUTER_SIZE - MIDDLE_SIZE) / 2,BOARD_TOP + (OUTER_SIZE - MIDDLE_SIZE) / 2,),
    6: (BOARD_LEFT + (OUTER_SIZE - INNER_SIZE) / 2,BOARD_TOP + (OUTER_SIZE - INNER_SIZE) / 2,),
    7: (BOARD_LEFT + OUTER_SIZE / 2,BOARD_TOP + (OUTER_SIZE - INNER_SIZE) / 2,),
    8: (BOARD_LEFT + OUTER_SIZE - (OUTER_SIZE - INNER_SIZE) / 2,BOARD_TOP + (OUTER_SIZE - INNER_SIZE) / 2,),
    9: (BOARD_LEFT,BOARD_TOP + OUTER_SIZE / 2,),
    10: (BOARD_LEFT + (OUTER_SIZE - MIDDLE_SIZE) / 2,BOARD_TOP + OUTER_SIZE / 2,),
    11: (BOARD_LEFT + (OUTER_SIZE - INNER_SIZE) / 2,BOARD_TOP + OUTER_SIZE / 2,),
    12: (BOARD_LEFT + OUTER_SIZE - (OUTER_SIZE - INNER_SIZE) / 2,BOARD_TOP + OUTER_SIZE / 2,),
    13: (BOARD_LEFT + OUTER_SIZE - (OUTER_SIZE - MIDDLE_SIZE) / 2,BOARD_TOP + OUTER_SIZE / 2,),
    14: (BOARD_LEFT + OUTER_SIZE,BOARD_TOP + OUTER_SIZE / 2,),
    15: (BOARD_LEFT + (OUTER_SIZE - INNER_SIZE) / 2,BOARD_TOP + OUTER_SIZE - (OUTER_SIZE - INNER_SIZE) / 2,),
    16: (BOARD_LEFT + OUTER_SIZE / 2,BOARD_TOP + OUTER_SIZE - (OUTER_SIZE - INNER_SIZE) / 2,),
    17: (BOARD_LEFT + OUTER_SIZE - (OUTER_SIZE - INNER_SIZE) / 2,BOARD_TOP + OUTER_SIZE - (OUTER_SIZE - INNER_SIZE) / 2,),
    18: (BOARD_LEFT + (OUTER_SIZE - MIDDLE_SIZE) / 2,BOARD_TOP + OUTER_SIZE - (OUTER_SIZE - MIDDLE_SIZE) / 2,),
    19: (BOARD_LEFT + OUTER_SIZE / 2,BOARD_TOP + OUTER_SIZE - (OUTER_SIZE - MIDDLE_SIZE) / 2,),
    20: (BOARD_LEFT + OUTER_SIZE - (OUTER_SIZE - MIDDLE_SIZE) / 2,BOARD_TOP + OUTER_SIZE - (OUTER_SIZE - MIDDLE_SIZE) / 2,),
    21: (BOARD_LEFT,BOARD_TOP + OUTER_SIZE,),
    22: (BOARD_LEFT + OUTER_SIZE / 2,BOARD_TOP + OUTER_SIZE,),
    23: (BOARD_LEFT + OUTER_SIZE,BOARD_TOP + OUTER_SIZE,),
}