# engine/__init__.py
from engine.version import ENGINE_NAME, ENGINE_VERSION, PHASE, STATUS
_LAZY_IMPORTS = {"GameInterface": ("engine.interfaces.game_interface", "GameInterface"),"AIInterface": ("engine.interfaces.ai_interface", "AIInterface"),"AIDifficulty": ("engine.interfaces.ai_interface", "AIDifficulty"),"BoardInterface": ("engine.interfaces.board_interface", "BoardInterface"),"SceneInterface": ("engine.interfaces.scene_interface", "SceneInterface"),"GameResult": ("engine.interfaces.game_result", "GameResult"),"TerminationReason": ("engine.interfaces.game_result", "TerminationReason"),"GameBase": ("engine.game_base", "GameBase"),"AIBase": ("engine.ai_base", "AIBase"),"GridBoard": ("engine.board.grid_board", "GridBoard"),"IntersectionBoard": ("engine.board.intersection_board", "IntersectionBoard"),"GraphBoard": ("engine.board.graph_board", "GraphBoard"),"MinimaxEngine": ("engine.ai.minimax", "MinimaxEngine"),"MCTSEngine": ("engine.ai.mcts", "MCTSEngine"),"TranspositionTable": ("engine.ai.transposition_table", "TranspositionTable"),"RandomAI": ("engine.ai.random_ai", "RandomAI"),"get_event_manager": ("engine.core.event_manager", "get_event_manager"),"reset_event_manager": ("engine.core.event_manager", "reset_event_manager"),"EventManager": ("engine.core.event_manager", "EventManager"),"StateManager": ("engine.core.state_manager", "StateManager"),"MoveRecord": ("engine.core.state_manager", "MoveRecord"),"GridCoordinateMapper": ("engine.core.coordinate_mapper", "GridCoordinateMapper"),"CoordinateMapper": ("engine.core.coordinate_mapper", "CoordinateMapper"),"Trajectory": ("engine.core.animation", "Trajectory"),"SlideTrajectory": ("engine.core.animation", "SlideTrajectory"),"ArcTrajectory": ("engine.core.animation", "ArcTrajectory"),"DropTrajectory": ("engine.core.animation", "DropTrajectory"),"FlipTrajectory": ("engine.core.animation", "FlipTrajectory"),"LinearTrajectory": ("engine.core.animation", "LinearTrajectory"),"Difficulty": ("engine.utils.constants", "Difficulty"),"GameMode": ("engine.utils.constants", "GameMode"),"GameState": ("engine.utils.constants", "GameState"),"EventType": ("engine.utils.constants", "EventType"),"clamp": ("engine.utils.helpers", "clamp"),"lerp": ("engine.utils.helpers", "lerp"),"board_to_fen": ("engine.utils.serialization", "board_to_fen"),"fen_to_board": ("engine.utils.serialization", "fen_to_board"),"export_sgf": ("engine.utils.serialization", "export_sgf"),"export_pgn": ("engine.utils.serialization", "export_pgn"),"export_pdn": ("engine.utils.serialization", "export_pdn"),"serialize_game_state": ("engine.utils.serialization", "serialize_game_state"),"deserialize_game_state": ("engine.utils.serialization", "deserialize_game_state"),}
def __getattr__(name: str):
    if name in _LAZY_IMPORTS:
        import importlib
        module_path, obj_name = _LAZY_IMPORTS[name]
        module = importlib.import_module(module_path)
        obj = getattr(module, obj_name)
        globals()[name] = obj
        return obj
    raise AttributeError(f"module 'engine' has no attribute {name!r}")
__all__ = ["ENGINE_NAME","ENGINE_VERSION","PHASE","STATUS",*_LAZY_IMPORTS.keys(),]